version: '3'
services:
    cache:
        image: redis:alpine
        command: redis-server
        ports:
            - 6379:6379
    bb-model-controller:
        image: betterboxd-model-controller:1.0
        ports:
            - 3001:3001
        environment:
            - ACCESS_TOKEN=2f1af7050fe78c07a33b214957f10d8e22d2ccdb5c7d0a54b5cab3f605d14812
            - CLIENT_ID=bc41e949718972a33a26d24d177fa2cbfc46a32172fcb7af3d745b5aa5a21f6d
            - CLIENT_SECRET=d0b574a73386a09a723b205ab7a42e7108b304fab503f9cca59b00165c1dd1e5
            - REDIS_HOST=cache
            - REDIS_PORT=6379
            - FANART_KEY=bfb7ffd7bab1e6e5c16919fc2c6ff6ad
            - MONGO_URI=mongodb+srv://betterboxd:movie@main.6pjwu.mongodb.net/BetterBoxd?retryWrites=true&w=majority
        depends_on:
            - bb-redis
    bb-view:
        image: betterboxd-view:1.0
        ports:
            - 3000:3000
